FROM python:3.11-slim

ENV CALENDARS=__CALENDARS__
ENV LANG=__LANG__
ENV DOMAIN=__DOMAIN__

WORKDIR /app
COPY . /app

# Здесь может быть установка зависимостей и запуск приложения
CMD ["python", "app.py"] 